### ISSUE TITLE
Broken on React 15.4.0

### ISSUE THREAD

**Issue by kegsay** [sstur/draft-js-utils#54] opened 2016-11-17 09:29 UTC
Fails with:

```
Error: Cannot find module "react/lib/CSSProperty"
ERROR in ./~/draft-js-export-html/lib/helpers/styleToCSS.js
Module not found: Error: Cannot resolve 'file' or 'directory' /[...]/node_modules/react/lib/CSSProperty in /[...]/node_modules/draft-js-export-html/lib/helpers
 @ ./~/draft-js-export-html/lib/helpers/styleToCSS.js 7:19-51
```

Probably because of:

> React package and browser build no longer "secretly" includes React DOM. (@sebmarkbage in #7164 and #7168)

So there is no `CSSProperty` anymore.

**Comment by richvdh** [comment] 2016-11-17 10:11
Actually this looks like a duplicate of #51, which is already fixed

**Closed as completed** 2016-11-17 10:13 UTC
